### ISSUE TITLE
Prints content-type in `spry_multer`

### ISSUE THREAD

**Issue by SirusCodes** [odroe/spry#18]
When I implemented spry_multer in my project it added unnecessary logs in my command-line. 

![image](https://user-images.githubusercontent.com/50910066/221347952-27d640ba-c2cf-45c6-81ec-b052469bb9df.png)

I don't think that it should be done as it degrades the raw performance and also it pollutes the logs which are not required.

Culprit:
https://github.com/odroe/spry/blob/e904cc7f5fcb6bf8707dfe7fb8f8ed97bec4c2ab/packages/spry_multer/lib/src/_internal/multer_impl.dart#L44

**Comment by medz** [comment]
Fixed in `0.0.2` version
